# coding: utf-8


anamnesis_gyn_data = {
    'age': 1,
    'duration': '1',
    'period_duration': '1',
    'disorder': True,
    'menstrual_character': ['blood_clot', 'excessive'],
    'intermenstrual_spotting': 'z',
    'menstrual_pain': 'z',
    'menopause': False,
    'menopause_age': 1,
    'sex_life_age': 1,
    'intercourse_partner_number': 1,
    'marital_status': '01',
    'std': ['clamidiosis', 'condyloma', 'cytomegalovirus'],
    'gynecopathy': ['adnexitis'],
    'hepatitis': 'z',
    'tuberculosis': 'z',
    'somatic_disease': 'z',
    # 'hereditary': [],
    # 'gyn_operation': '',
    'infertility': False,
    # 'infertility_kind': '',
    # 'infertility_duration': 1,
    # 'infertility_etiology': [],
    # 'infertility_treatment': [],
    # 'traumas': '',
    # 'operations': '',
    'alcohol': True,
    'smoking': True,
    'drugs': False,
    'toxic': False,
    'work_group': '01',
    'professional_properties': 'chemical_factors',
    'additional_info': '789',
    'epidemic': 'z',
}
