# -*- encoding: utf-8 -*-
#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface(object):
  def getAvailableAccounts(self, ):
    """
    Получение всех доступных счетов (deleted = 0), в случае если счетов нету - пустой сисок.
    @return список счетов
    """
    pass

  def getAccount(self, accountId):
    """
    Получение одного счета по его идентификатору
    @param accountId : идентификатор счета
    @throw NotFoundException nfExc : Если нету счета с таким идентификатором
    @return Счет / Ошибка

    Parameters:
     - accountId
    """
    pass

  def getAccountItems(self, accountId):
    """
    Получение всех позиций счета по идентификатору счета
    @param accountId : идентификатор счета по которому будут возвращены позиции
    @throw NotFoundException nfExc : Если нету счета с таким идентификатором
    @return Список позиций счета или пустой список если на счет нету ни одной позиции

    Parameters:
     - accountId
    """
    pass

  def setDoNotUploadAnymoreMarks(self, items):
    """
    Проставление отметки "не выгружать более" для заданных позиций счета
    @param items Список структур позиций счета, которых более не требуется выгружать ни в одном счете

    Parameters:
     - items
    """
    pass

  def deleteAccount(self, accountId):
    """
    Parameters:
     - accountId
    """
    pass

  def getXMLRegisters(self, contractId, beginDate, endDate, infisCode, obsoleteInfisCode, smoNumber, orgStructureIdList, patientOptionalFields, personOptionalFields, sluchOptionalFields, primaryAccount, levelMO):
    """
    Parameters:
     - contractId
     - beginDate
     - endDate
     - infisCode
     - obsoleteInfisCode
     - smoNumber
     - orgStructureIdList
     - patientOptionalFields
     - personOptionalFields
     - sluchOptionalFields
     - primaryAccount
     - levelMO
    """
    pass

  def getOrgStructures(self, organisationInfis):
    """
    Получение всех подразделений у которых  инфис-код ЛПУ совпадает с заданным
    @param organisationInfis             1)Инфис код ЛПУ для которого необходимо вернуть подразделения
    @throw InvalidOrganizationInfisException  когда нету организации с таким инфис-кодом

    Parameters:
     - organisationInfis
    """
    pass

  def getAvailableContracts(self, organisationInfis):
    """
    Получение всех контрактов, где получателем является заданное ЛПУ
    @param organisationInfis            1)Инфис код ЛПУ для которого необходимо вернуть контракту
    @throw InvalidOrganizationInfisException  когда нету организации с таким инфис-кодом

    Parameters:
     - organisationInfis
    """
    pass

  def changeClientPolicy(self, patientId, newPolicy):
    """
    Загрузка измененных данных от ТФОМС

    Parameters:
     - patientId
     - newPolicy
    """
    pass

  def loadTfomsPayments(self, fileName, payments, refusedAmount, payedAmount, payedSum, refusedSum, accountNumber, comment):
    """
    загрузка результатов оплаты случаев из ТФОМС
    @param fileName имя файла в котором содержатся результаты ответа из ТФОМС
    @param payments список структур с данными об оплате случая
    @param refusedAmount количество отказанных случаев
    @param payedAmount количество оплаченных случаев
    @param payedSum  оплаченная сумма
    @param refusedSum отказнная в оплате сумма
    @param accountNumber номер счета
    @param comment   комментарий к счету
    @return map<int, string> карта вида <идентификатор позиции счета, текст ошибки>
    или пустой список если все ок
    @throw  NotFoundException когда в БД ЛПУ нету счета с таким номером

    Parameters:
     - fileName
     - payments
     - refusedAmount
     - payedAmount
     - payedSum
     - refusedSum
     - accountNumber
     - comment
    """
    pass


class Client(Iface):
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot is not None:
      self._oprot = oprot
    self._seqid = 0

  def getAvailableAccounts(self, ):
    """
    Получение всех доступных счетов (deleted = 0), в случае если счетов нету - пустой сисок.
    @return список счетов
    """
    self.send_getAvailableAccounts()
    return self.recv_getAvailableAccounts()

  def send_getAvailableAccounts(self, ):
    self._oprot.writeMessageBegin('getAvailableAccounts', TMessageType.CALL, self._seqid)
    args = getAvailableAccounts_args()
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getAvailableAccounts(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = getAvailableAccounts_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getAvailableAccounts failed: unknown result");

  def getAccount(self, accountId):
    """
    Получение одного счета по его идентификатору
    @param accountId : идентификатор счета
    @throw NotFoundException nfExc : Если нету счета с таким идентификатором
    @return Счет / Ошибка

    Parameters:
     - accountId
    """
    self.send_getAccount(accountId)
    return self.recv_getAccount()

  def send_getAccount(self, accountId):
    self._oprot.writeMessageBegin('getAccount', TMessageType.CALL, self._seqid)
    args = getAccount_args()
    args.accountId = accountId
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getAccount(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = getAccount_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.nfExc is not None:
      raise result.nfExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getAccount failed: unknown result");

  def getAccountItems(self, accountId):
    """
    Получение всех позиций счета по идентификатору счета
    @param accountId : идентификатор счета по которому будут возвращены позиции
    @throw NotFoundException nfExc : Если нету счета с таким идентификатором
    @return Список позиций счета или пустой список если на счет нету ни одной позиции

    Parameters:
     - accountId
    """
    self.send_getAccountItems(accountId)
    return self.recv_getAccountItems()

  def send_getAccountItems(self, accountId):
    self._oprot.writeMessageBegin('getAccountItems', TMessageType.CALL, self._seqid)
    args = getAccountItems_args()
    args.accountId = accountId
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getAccountItems(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = getAccountItems_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.nfExc is not None:
      raise result.nfExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getAccountItems failed: unknown result");

  def setDoNotUploadAnymoreMarks(self, items):
    """
    Проставление отметки "не выгружать более" для заданных позиций счета
    @param items Список структур позиций счета, которых более не требуется выгружать ни в одном счете

    Parameters:
     - items
    """
    self.send_setDoNotUploadAnymoreMarks(items)

  def send_setDoNotUploadAnymoreMarks(self, items):
    self._oprot.writeMessageBegin('setDoNotUploadAnymoreMarks', TMessageType.CALL, self._seqid)
    args = setDoNotUploadAnymoreMarks_args()
    args.items = items
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()
  def deleteAccount(self, accountId):
    """
    Parameters:
     - accountId
    """
    self.send_deleteAccount(accountId)
    return self.recv_deleteAccount()

  def send_deleteAccount(self, accountId):
    self._oprot.writeMessageBegin('deleteAccount', TMessageType.CALL, self._seqid)
    args = deleteAccount_args()
    args.accountId = accountId
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_deleteAccount(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = deleteAccount_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "deleteAccount failed: unknown result");

  def getXMLRegisters(self, contractId, beginDate, endDate, infisCode, obsoleteInfisCode, smoNumber, orgStructureIdList, patientOptionalFields, personOptionalFields, sluchOptionalFields, primaryAccount, levelMO):
    """
    Parameters:
     - contractId
     - beginDate
     - endDate
     - infisCode
     - obsoleteInfisCode
     - smoNumber
     - orgStructureIdList
     - patientOptionalFields
     - personOptionalFields
     - sluchOptionalFields
     - primaryAccount
     - levelMO
    """
    self.send_getXMLRegisters(contractId, beginDate, endDate, infisCode, obsoleteInfisCode, smoNumber, orgStructureIdList, patientOptionalFields, personOptionalFields, sluchOptionalFields, primaryAccount, levelMO)
    return self.recv_getXMLRegisters()

  def send_getXMLRegisters(self, contractId, beginDate, endDate, infisCode, obsoleteInfisCode, smoNumber, orgStructureIdList, patientOptionalFields, personOptionalFields, sluchOptionalFields, primaryAccount, levelMO):
    self._oprot.writeMessageBegin('getXMLRegisters', TMessageType.CALL, self._seqid)
    args = getXMLRegisters_args()
    args.contractId = contractId
    args.beginDate = beginDate
    args.endDate = endDate
    args.infisCode = infisCode
    args.obsoleteInfisCode = obsoleteInfisCode
    args.smoNumber = smoNumber
    args.orgStructureIdList = orgStructureIdList
    args.patientOptionalFields = patientOptionalFields
    args.personOptionalFields = personOptionalFields
    args.sluchOptionalFields = sluchOptionalFields
    args.primaryAccount = primaryAccount
    args.levelMO = levelMO
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getXMLRegisters(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = getXMLRegisters_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.infisExc is not None:
      raise result.infisExc
    if result.contractExc is not None:
      raise result.contractExc
    if result.datesExc is not None:
      raise result.datesExc
    if result.invExc is not None:
      raise result.invExc
    if result.nfExc is not None:
      raise result.nfExc
    if result.sqlExc is not None:
      raise result.sqlExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getXMLRegisters failed: unknown result");

  def getOrgStructures(self, organisationInfis):
    """
    Получение всех подразделений у которых  инфис-код ЛПУ совпадает с заданным
    @param organisationInfis             1)Инфис код ЛПУ для которого необходимо вернуть подразделения
    @throw InvalidOrganizationInfisException  когда нету организации с таким инфис-кодом

    Parameters:
     - organisationInfis
    """
    self.send_getOrgStructures(organisationInfis)
    return self.recv_getOrgStructures()

  def send_getOrgStructures(self, organisationInfis):
    self._oprot.writeMessageBegin('getOrgStructures', TMessageType.CALL, self._seqid)
    args = getOrgStructures_args()
    args.organisationInfis = organisationInfis
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getOrgStructures(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = getOrgStructures_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.infisExc is not None:
      raise result.infisExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getOrgStructures failed: unknown result");

  def getAvailableContracts(self, organisationInfis):
    """
    Получение всех контрактов, где получателем является заданное ЛПУ
    @param organisationInfis            1)Инфис код ЛПУ для которого необходимо вернуть контракту
    @throw InvalidOrganizationInfisException  когда нету организации с таким инфис-кодом

    Parameters:
     - organisationInfis
    """
    self.send_getAvailableContracts(organisationInfis)
    return self.recv_getAvailableContracts()

  def send_getAvailableContracts(self, organisationInfis):
    self._oprot.writeMessageBegin('getAvailableContracts', TMessageType.CALL, self._seqid)
    args = getAvailableContracts_args()
    args.organisationInfis = organisationInfis
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getAvailableContracts(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = getAvailableContracts_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.infisExc is not None:
      raise result.infisExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getAvailableContracts failed: unknown result");

  def changeClientPolicy(self, patientId, newPolicy):
    """
    Загрузка измененных данных от ТФОМС

    Parameters:
     - patientId
     - newPolicy
    """
    self.send_changeClientPolicy(patientId, newPolicy)
    return self.recv_changeClientPolicy()

  def send_changeClientPolicy(self, patientId, newPolicy):
    self._oprot.writeMessageBegin('changeClientPolicy', TMessageType.CALL, self._seqid)
    args = changeClientPolicy_args()
    args.patientId = patientId
    args.newPolicy = newPolicy
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_changeClientPolicy(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = changeClientPolicy_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.argExc is not None:
      raise result.argExc
    if result.sqlExc is not None:
      raise result.sqlExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "changeClientPolicy failed: unknown result");

  def loadTfomsPayments(self, fileName, payments, refusedAmount, payedAmount, payedSum, refusedSum, accountNumber, comment):
    """
    загрузка результатов оплаты случаев из ТФОМС
    @param fileName имя файла в котором содержатся результаты ответа из ТФОМС
    @param payments список структур с данными об оплате случая
    @param refusedAmount количество отказанных случаев
    @param payedAmount количество оплаченных случаев
    @param payedSum  оплаченная сумма
    @param refusedSum отказнная в оплате сумма
    @param accountNumber номер счета
    @param comment   комментарий к счету
    @return map<int, string> карта вида <идентификатор позиции счета, текст ошибки>
    или пустой список если все ок
    @throw  NotFoundException когда в БД ЛПУ нету счета с таким номером

    Parameters:
     - fileName
     - payments
     - refusedAmount
     - payedAmount
     - payedSum
     - refusedSum
     - accountNumber
     - comment
    """
    self.send_loadTfomsPayments(fileName, payments, refusedAmount, payedAmount, payedSum, refusedSum, accountNumber, comment)
    return self.recv_loadTfomsPayments()

  def send_loadTfomsPayments(self, fileName, payments, refusedAmount, payedAmount, payedSum, refusedSum, accountNumber, comment):
    self._oprot.writeMessageBegin('loadTfomsPayments', TMessageType.CALL, self._seqid)
    args = loadTfomsPayments_args()
    args.fileName = fileName
    args.payments = payments
    args.refusedAmount = refusedAmount
    args.payedAmount = payedAmount
    args.payedSum = payedSum
    args.refusedSum = refusedSum
    args.accountNumber = accountNumber
    args.comment = comment
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_loadTfomsPayments(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = loadTfomsPayments_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.nfExc is not None:
      raise result.nfExc
    raise TApplicationException(TApplicationException.MISSING_RESULT, "loadTfomsPayments failed: unknown result");


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["getAvailableAccounts"] = Processor.process_getAvailableAccounts
    self._processMap["getAccount"] = Processor.process_getAccount
    self._processMap["getAccountItems"] = Processor.process_getAccountItems
    self._processMap["setDoNotUploadAnymoreMarks"] = Processor.process_setDoNotUploadAnymoreMarks
    self._processMap["deleteAccount"] = Processor.process_deleteAccount
    self._processMap["getXMLRegisters"] = Processor.process_getXMLRegisters
    self._processMap["getOrgStructures"] = Processor.process_getOrgStructures
    self._processMap["getAvailableContracts"] = Processor.process_getAvailableContracts
    self._processMap["changeClientPolicy"] = Processor.process_changeClientPolicy
    self._processMap["loadTfomsPayments"] = Processor.process_loadTfomsPayments

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_getAvailableAccounts(self, seqid, iprot, oprot):
    args = getAvailableAccounts_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getAvailableAccounts_result()
    result.success = self._handler.getAvailableAccounts()
    oprot.writeMessageBegin("getAvailableAccounts", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_getAccount(self, seqid, iprot, oprot):
    args = getAccount_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getAccount_result()
    try:
      result.success = self._handler.getAccount(args.accountId)
    except NotFoundException as nfExc:
      result.nfExc = nfExc
    oprot.writeMessageBegin("getAccount", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_getAccountItems(self, seqid, iprot, oprot):
    args = getAccountItems_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getAccountItems_result()
    try:
      result.success = self._handler.getAccountItems(args.accountId)
    except NotFoundException as nfExc:
      result.nfExc = nfExc
    oprot.writeMessageBegin("getAccountItems", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_setDoNotUploadAnymoreMarks(self, seqid, iprot, oprot):
    args = setDoNotUploadAnymoreMarks_args()
    args.read(iprot)
    iprot.readMessageEnd()
    self._handler.setDoNotUploadAnymoreMarks(args.items)
    return

  def process_deleteAccount(self, seqid, iprot, oprot):
    args = deleteAccount_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = deleteAccount_result()
    result.success = self._handler.deleteAccount(args.accountId)
    oprot.writeMessageBegin("deleteAccount", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_getXMLRegisters(self, seqid, iprot, oprot):
    args = getXMLRegisters_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getXMLRegisters_result()
    try:
      result.success = self._handler.getXMLRegisters(args.contractId, args.beginDate, args.endDate, args.infisCode, args.obsoleteInfisCode, args.smoNumber, args.orgStructureIdList, args.patientOptionalFields, args.personOptionalFields, args.sluchOptionalFields, args.primaryAccount, args.levelMO)
    except InvalidOrganizationInfisException as infisExc:
      result.infisExc = infisExc
    except InvalidContractException as contractExc:
      result.contractExc = contractExc
    except InvalidDateIntervalException as datesExc:
      result.datesExc = datesExc
    except InvalidArgumentException as invExc:
      result.invExc = invExc
    except NotFoundException as nfExc:
      result.nfExc = nfExc
    except SQLException as sqlExc:
      result.sqlExc = sqlExc
    oprot.writeMessageBegin("getXMLRegisters", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_getOrgStructures(self, seqid, iprot, oprot):
    args = getOrgStructures_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getOrgStructures_result()
    try:
      result.success = self._handler.getOrgStructures(args.organisationInfis)
    except InvalidOrganizationInfisException as infisExc:
      result.infisExc = infisExc
    oprot.writeMessageBegin("getOrgStructures", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_getAvailableContracts(self, seqid, iprot, oprot):
    args = getAvailableContracts_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getAvailableContracts_result()
    try:
      result.success = self._handler.getAvailableContracts(args.organisationInfis)
    except InvalidOrganizationInfisException as infisExc:
      result.infisExc = infisExc
    oprot.writeMessageBegin("getAvailableContracts", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_changeClientPolicy(self, seqid, iprot, oprot):
    args = changeClientPolicy_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = changeClientPolicy_result()
    try:
      result.success = self._handler.changeClientPolicy(args.patientId, args.newPolicy)
    except InvalidArgumentException as argExc:
      result.argExc = argExc
    except SQLException as sqlExc:
      result.sqlExc = sqlExc
    oprot.writeMessageBegin("changeClientPolicy", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_loadTfomsPayments(self, seqid, iprot, oprot):
    args = loadTfomsPayments_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = loadTfomsPayments_result()
    try:
      result.success = self._handler.loadTfomsPayments(args.fileName, args.payments, args.refusedAmount, args.payedAmount, args.payedSum, args.refusedSum, args.accountNumber, args.comment)
    except NotFoundException as nfExc:
      result.nfExc = nfExc
    oprot.writeMessageBegin("loadTfomsPayments", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class getAvailableAccounts_args(object):

  thrift_spec = (
  )

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAvailableAccounts_args')
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAvailableAccounts_result(object):
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.LIST, 'success', (TType.STRUCT,(Account, Account.thrift_spec)), None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.LIST:
          self.success = []
          (_etype40, _size37) = iprot.readListBegin()
          for _i41 in xrange(_size37):
            _elem42 = Account()
            _elem42.read(iprot)
            self.success.append(_elem42)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAvailableAccounts_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.LIST, 0)
      oprot.writeListBegin(TType.STRUCT, len(self.success))
      for iter43 in self.success:
        iter43.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAccount_args(object):
  """
  Attributes:
   - accountId
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'accountId', None, None, ), # 1
  )

  def __init__(self, accountId=None,):
    self.accountId = accountId

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.accountId = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAccount_args')
    if self.accountId is not None:
      oprot.writeFieldBegin('accountId', TType.I32, 1)
      oprot.writeI32(self.accountId)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAccount_result(object):
  """
  Attributes:
   - success
   - nfExc
  """

  thrift_spec = (
    (0, TType.STRUCT, 'success', (Account, Account.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'nfExc', (NotFoundException, NotFoundException.thrift_spec), None, ), # 1
  )

  def __init__(self, success=None, nfExc=None,):
    self.success = success
    self.nfExc = nfExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = Account()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.nfExc = NotFoundException()
          self.nfExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAccount_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.nfExc is not None:
      oprot.writeFieldBegin('nfExc', TType.STRUCT, 1)
      self.nfExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAccountItems_args(object):
  """
  Attributes:
   - accountId
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'accountId', None, None, ), # 1
  )

  def __init__(self, accountId=None,):
    self.accountId = accountId

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.accountId = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAccountItems_args')
    if self.accountId is not None:
      oprot.writeFieldBegin('accountId', TType.I32, 1)
      oprot.writeI32(self.accountId)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAccountItems_result(object):
  """
  Attributes:
   - success
   - nfExc
  """

  thrift_spec = (
    (0, TType.STRUCT, 'success', (AccountInfo, AccountInfo.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'nfExc', (NotFoundException, NotFoundException.thrift_spec), None, ), # 1
  )

  def __init__(self, success=None, nfExc=None,):
    self.success = success
    self.nfExc = nfExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = AccountInfo()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.nfExc = NotFoundException()
          self.nfExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAccountItems_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.nfExc is not None:
      oprot.writeFieldBegin('nfExc', TType.STRUCT, 1)
      self.nfExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class setDoNotUploadAnymoreMarks_args(object):
  """
  Attributes:
   - items
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'items', (TType.STRUCT,(AccountItemWithMark, AccountItemWithMark.thrift_spec)), None, ), # 1
  )

  def __init__(self, items=None,):
    self.items = items

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.items = []
          (_etype47, _size44) = iprot.readListBegin()
          for _i48 in xrange(_size44):
            _elem49 = AccountItemWithMark()
            _elem49.read(iprot)
            self.items.append(_elem49)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('setDoNotUploadAnymoreMarks_args')
    if self.items is not None:
      oprot.writeFieldBegin('items', TType.LIST, 1)
      oprot.writeListBegin(TType.STRUCT, len(self.items))
      for iter50 in self.items:
        iter50.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class deleteAccount_args(object):
  """
  Attributes:
   - accountId
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'accountId', None, None, ), # 1
  )

  def __init__(self, accountId=None,):
    self.accountId = accountId

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.accountId = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('deleteAccount_args')
    if self.accountId is not None:
      oprot.writeFieldBegin('accountId', TType.I32, 1)
      oprot.writeI32(self.accountId)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class deleteAccount_result(object):
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.BOOL, 'success', None, None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.BOOL:
          self.success = iprot.readBool();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('deleteAccount_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.BOOL, 0)
      oprot.writeBool(self.success)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getXMLRegisters_args(object):
  """
  Attributes:
   - contractId
   - beginDate
   - endDate
   - infisCode
   - obsoleteInfisCode
   - smoNumber
   - orgStructureIdList
   - patientOptionalFields
   - personOptionalFields
   - sluchOptionalFields
   - primaryAccount
   - levelMO
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'contractId', None, None, ), # 1
    (2, TType.I64, 'beginDate', None, None, ), # 2
    (3, TType.I64, 'endDate', None, None, ), # 3
    (4, TType.STRING, 'infisCode', None, None, ), # 4
    (5, TType.STRING, 'obsoleteInfisCode', None, None, ), # 5
    (6, TType.STRING, 'smoNumber', None, None, ), # 6
    (7, TType.LIST, 'orgStructureIdList', (TType.I32,None), None, ), # 7
    (8, TType.SET, 'patientOptionalFields', (TType.I32,None), None, ), # 8
    (9, TType.SET, 'personOptionalFields', (TType.I32,None), None, ), # 9
    (10, TType.SET, 'sluchOptionalFields', (TType.I32,None), None, ), # 10
    (11, TType.BOOL, 'primaryAccount', None, None, ), # 11
    (12, TType.STRING, 'levelMO', None, None, ), # 12
  )

  def __init__(self, contractId=None, beginDate=None, endDate=None, infisCode=None, obsoleteInfisCode=None, smoNumber=None, orgStructureIdList=None, patientOptionalFields=None, personOptionalFields=None, sluchOptionalFields=None, primaryAccount=None, levelMO=None,):
    self.contractId = contractId
    self.beginDate = beginDate
    self.endDate = endDate
    self.infisCode = infisCode
    self.obsoleteInfisCode = obsoleteInfisCode
    self.smoNumber = smoNumber
    self.orgStructureIdList = orgStructureIdList
    self.patientOptionalFields = patientOptionalFields
    self.personOptionalFields = personOptionalFields
    self.sluchOptionalFields = sluchOptionalFields
    self.primaryAccount = primaryAccount
    self.levelMO = levelMO

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.contractId = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I64:
          self.beginDate = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I64:
          self.endDate = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.infisCode = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.obsoleteInfisCode = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.smoNumber = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.LIST:
          self.orgStructureIdList = []
          (_etype54, _size51) = iprot.readListBegin()
          for _i55 in xrange(_size51):
            _elem56 = iprot.readI32();
            self.orgStructureIdList.append(_elem56)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.SET:
          self.patientOptionalFields = set()
          (_etype60, _size57) = iprot.readSetBegin()
          for _i61 in xrange(_size57):
            _elem62 = iprot.readI32();
            self.patientOptionalFields.add(_elem62)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.SET:
          self.personOptionalFields = set()
          (_etype66, _size63) = iprot.readSetBegin()
          for _i67 in xrange(_size63):
            _elem68 = iprot.readI32();
            self.personOptionalFields.add(_elem68)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.SET:
          self.sluchOptionalFields = set()
          (_etype72, _size69) = iprot.readSetBegin()
          for _i73 in xrange(_size69):
            _elem74 = iprot.readI32();
            self.sluchOptionalFields.add(_elem74)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.BOOL:
          self.primaryAccount = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.levelMO = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getXMLRegisters_args')
    if self.contractId is not None:
      oprot.writeFieldBegin('contractId', TType.I32, 1)
      oprot.writeI32(self.contractId)
      oprot.writeFieldEnd()
    if self.beginDate is not None:
      oprot.writeFieldBegin('beginDate', TType.I64, 2)
      oprot.writeI64(self.beginDate)
      oprot.writeFieldEnd()
    if self.endDate is not None:
      oprot.writeFieldBegin('endDate', TType.I64, 3)
      oprot.writeI64(self.endDate)
      oprot.writeFieldEnd()
    if self.infisCode is not None:
      oprot.writeFieldBegin('infisCode', TType.STRING, 4)
      oprot.writeString(self.infisCode.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.obsoleteInfisCode is not None:
      oprot.writeFieldBegin('obsoleteInfisCode', TType.STRING, 5)
      oprot.writeString(self.obsoleteInfisCode.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.smoNumber is not None:
      oprot.writeFieldBegin('smoNumber', TType.STRING, 6)
      oprot.writeString(self.smoNumber.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.orgStructureIdList is not None:
      oprot.writeFieldBegin('orgStructureIdList', TType.LIST, 7)
      oprot.writeListBegin(TType.I32, len(self.orgStructureIdList))
      for iter75 in self.orgStructureIdList:
        oprot.writeI32(iter75)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.patientOptionalFields is not None:
      oprot.writeFieldBegin('patientOptionalFields', TType.SET, 8)
      oprot.writeSetBegin(TType.I32, len(self.patientOptionalFields))
      for iter76 in self.patientOptionalFields:
        oprot.writeI32(iter76)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    if self.personOptionalFields is not None:
      oprot.writeFieldBegin('personOptionalFields', TType.SET, 9)
      oprot.writeSetBegin(TType.I32, len(self.personOptionalFields))
      for iter77 in self.personOptionalFields:
        oprot.writeI32(iter77)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    if self.sluchOptionalFields is not None:
      oprot.writeFieldBegin('sluchOptionalFields', TType.SET, 10)
      oprot.writeSetBegin(TType.I32, len(self.sluchOptionalFields))
      for iter78 in self.sluchOptionalFields:
        oprot.writeI32(iter78)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    if self.primaryAccount is not None:
      oprot.writeFieldBegin('primaryAccount', TType.BOOL, 11)
      oprot.writeBool(self.primaryAccount)
      oprot.writeFieldEnd()
    if self.levelMO is not None:
      oprot.writeFieldBegin('levelMO', TType.STRING, 12)
      oprot.writeString(self.levelMO.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getXMLRegisters_result(object):
  """
  Attributes:
   - success
   - infisExc
   - contractExc
   - datesExc
   - invExc
   - nfExc
   - sqlExc
  """

  thrift_spec = (
    (0, TType.STRUCT, 'success', (XMLRegisters, XMLRegisters.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'infisExc', (InvalidOrganizationInfisException, InvalidOrganizationInfisException.thrift_spec), None, ), # 1
    (2, TType.STRUCT, 'contractExc', (InvalidContractException, InvalidContractException.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'datesExc', (InvalidDateIntervalException, InvalidDateIntervalException.thrift_spec), None, ), # 3
    (4, TType.STRUCT, 'invExc', (InvalidArgumentException, InvalidArgumentException.thrift_spec), None, ), # 4
    (5, TType.STRUCT, 'nfExc', (NotFoundException, NotFoundException.thrift_spec), None, ), # 5
    (6, TType.STRUCT, 'sqlExc', (SQLException, SQLException.thrift_spec), None, ), # 6
  )

  def __init__(self, success=None, infisExc=None, contractExc=None, datesExc=None, invExc=None, nfExc=None, sqlExc=None,):
    self.success = success
    self.infisExc = infisExc
    self.contractExc = contractExc
    self.datesExc = datesExc
    self.invExc = invExc
    self.nfExc = nfExc
    self.sqlExc = sqlExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = XMLRegisters()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.infisExc = InvalidOrganizationInfisException()
          self.infisExc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.contractExc = InvalidContractException()
          self.contractExc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.datesExc = InvalidDateIntervalException()
          self.datesExc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.invExc = InvalidArgumentException()
          self.invExc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRUCT:
          self.nfExc = NotFoundException()
          self.nfExc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRUCT:
          self.sqlExc = SQLException()
          self.sqlExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getXMLRegisters_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.infisExc is not None:
      oprot.writeFieldBegin('infisExc', TType.STRUCT, 1)
      self.infisExc.write(oprot)
      oprot.writeFieldEnd()
    if self.contractExc is not None:
      oprot.writeFieldBegin('contractExc', TType.STRUCT, 2)
      self.contractExc.write(oprot)
      oprot.writeFieldEnd()
    if self.datesExc is not None:
      oprot.writeFieldBegin('datesExc', TType.STRUCT, 3)
      self.datesExc.write(oprot)
      oprot.writeFieldEnd()
    if self.invExc is not None:
      oprot.writeFieldBegin('invExc', TType.STRUCT, 4)
      self.invExc.write(oprot)
      oprot.writeFieldEnd()
    if self.nfExc is not None:
      oprot.writeFieldBegin('nfExc', TType.STRUCT, 5)
      self.nfExc.write(oprot)
      oprot.writeFieldEnd()
    if self.sqlExc is not None:
      oprot.writeFieldBegin('sqlExc', TType.STRUCT, 6)
      self.sqlExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getOrgStructures_args(object):
  """
  Attributes:
   - organisationInfis
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'organisationInfis', None, None, ), # 1
  )

  def __init__(self, organisationInfis=None,):
    self.organisationInfis = organisationInfis

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.organisationInfis = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getOrgStructures_args')
    if self.organisationInfis is not None:
      oprot.writeFieldBegin('organisationInfis', TType.STRING, 1)
      oprot.writeString(self.organisationInfis.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getOrgStructures_result(object):
  """
  Attributes:
   - success
   - infisExc
  """

  thrift_spec = (
    (0, TType.LIST, 'success', (TType.STRUCT,(OrgStructure, OrgStructure.thrift_spec)), None, ), # 0
    (1, TType.STRUCT, 'infisExc', (InvalidOrganizationInfisException, InvalidOrganizationInfisException.thrift_spec), None, ), # 1
  )

  def __init__(self, success=None, infisExc=None,):
    self.success = success
    self.infisExc = infisExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.LIST:
          self.success = []
          (_etype82, _size79) = iprot.readListBegin()
          for _i83 in xrange(_size79):
            _elem84 = OrgStructure()
            _elem84.read(iprot)
            self.success.append(_elem84)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.infisExc = InvalidOrganizationInfisException()
          self.infisExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getOrgStructures_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.LIST, 0)
      oprot.writeListBegin(TType.STRUCT, len(self.success))
      for iter85 in self.success:
        iter85.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.infisExc is not None:
      oprot.writeFieldBegin('infisExc', TType.STRUCT, 1)
      self.infisExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAvailableContracts_args(object):
  """
  Attributes:
   - organisationInfis
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'organisationInfis', None, None, ), # 1
  )

  def __init__(self, organisationInfis=None,):
    self.organisationInfis = organisationInfis

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.organisationInfis = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAvailableContracts_args')
    if self.organisationInfis is not None:
      oprot.writeFieldBegin('organisationInfis', TType.STRING, 1)
      oprot.writeString(self.organisationInfis.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class getAvailableContracts_result(object):
  """
  Attributes:
   - success
   - infisExc
  """

  thrift_spec = (
    (0, TType.LIST, 'success', (TType.STRUCT,(Contract, Contract.thrift_spec)), None, ), # 0
    (1, TType.STRUCT, 'infisExc', (InvalidOrganizationInfisException, InvalidOrganizationInfisException.thrift_spec), None, ), # 1
  )

  def __init__(self, success=None, infisExc=None,):
    self.success = success
    self.infisExc = infisExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.LIST:
          self.success = []
          (_etype89, _size86) = iprot.readListBegin()
          for _i90 in xrange(_size86):
            _elem91 = Contract()
            _elem91.read(iprot)
            self.success.append(_elem91)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.infisExc = InvalidOrganizationInfisException()
          self.infisExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('getAvailableContracts_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.LIST, 0)
      oprot.writeListBegin(TType.STRUCT, len(self.success))
      for iter92 in self.success:
        iter92.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.infisExc is not None:
      oprot.writeFieldBegin('infisExc', TType.STRUCT, 1)
      self.infisExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class changeClientPolicy_args(object):
  """
  Attributes:
   - patientId
   - newPolicy
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'patientId', None, None, ), # 1
    (2, TType.STRUCT, 'newPolicy', (TClientPolicy, TClientPolicy.thrift_spec), None, ), # 2
  )

  def __init__(self, patientId=None, newPolicy=None,):
    self.patientId = patientId
    self.newPolicy = newPolicy

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.patientId = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.newPolicy = TClientPolicy()
          self.newPolicy.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('changeClientPolicy_args')
    if self.patientId is not None:
      oprot.writeFieldBegin('patientId', TType.I32, 1)
      oprot.writeI32(self.patientId)
      oprot.writeFieldEnd()
    if self.newPolicy is not None:
      oprot.writeFieldBegin('newPolicy', TType.STRUCT, 2)
      self.newPolicy.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class changeClientPolicy_result(object):
  """
  Attributes:
   - success
   - argExc
   - sqlExc
  """

  thrift_spec = (
    (0, TType.I32, 'success', None, None, ), # 0
    (1, TType.STRUCT, 'argExc', (InvalidArgumentException, InvalidArgumentException.thrift_spec), None, ), # 1
    (2, TType.STRUCT, 'sqlExc', (SQLException, SQLException.thrift_spec), None, ), # 2
  )

  def __init__(self, success=None, argExc=None, sqlExc=None,):
    self.success = success
    self.argExc = argExc
    self.sqlExc = sqlExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.I32:
          self.success = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.argExc = InvalidArgumentException()
          self.argExc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.sqlExc = SQLException()
          self.sqlExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('changeClientPolicy_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.I32, 0)
      oprot.writeI32(self.success)
      oprot.writeFieldEnd()
    if self.argExc is not None:
      oprot.writeFieldBegin('argExc', TType.STRUCT, 1)
      self.argExc.write(oprot)
      oprot.writeFieldEnd()
    if self.sqlExc is not None:
      oprot.writeFieldBegin('sqlExc', TType.STRUCT, 2)
      self.sqlExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class loadTfomsPayments_args(object):
  """
  Attributes:
   - fileName
   - payments
   - refusedAmount
   - payedAmount
   - payedSum
   - refusedSum
   - accountNumber
   - comment
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'fileName', None, None, ), # 1
    (2, TType.LIST, 'payments', (TType.STRUCT,(Payment, Payment.thrift_spec)), None, ), # 2
    (3, TType.I32, 'refusedAmount', None, None, ), # 3
    (4, TType.I32, 'payedAmount', None, None, ), # 4
    (5, TType.DOUBLE, 'payedSum', None, None, ), # 5
    (6, TType.DOUBLE, 'refusedSum', None, None, ), # 6
    (7, TType.STRING, 'accountNumber', None, None, ), # 7
    (8, TType.STRING, 'comment', None, None, ), # 8
  )

  def __init__(self, fileName=None, payments=None, refusedAmount=None, payedAmount=None, payedSum=None, refusedSum=None, accountNumber=None, comment=None,):
    self.fileName = fileName
    self.payments = payments
    self.refusedAmount = refusedAmount
    self.payedAmount = payedAmount
    self.payedSum = payedSum
    self.refusedSum = refusedSum
    self.accountNumber = accountNumber
    self.comment = comment

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.fileName = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.payments = []
          (_etype96, _size93) = iprot.readListBegin()
          for _i97 in xrange(_size93):
            _elem98 = Payment()
            _elem98.read(iprot)
            self.payments.append(_elem98)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.refusedAmount = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.payedAmount = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.DOUBLE:
          self.payedSum = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.DOUBLE:
          self.refusedSum = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.accountNumber = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.comment = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('loadTfomsPayments_args')
    if self.fileName is not None:
      oprot.writeFieldBegin('fileName', TType.STRING, 1)
      oprot.writeString(self.fileName.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.payments is not None:
      oprot.writeFieldBegin('payments', TType.LIST, 2)
      oprot.writeListBegin(TType.STRUCT, len(self.payments))
      for iter99 in self.payments:
        iter99.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.refusedAmount is not None:
      oprot.writeFieldBegin('refusedAmount', TType.I32, 3)
      oprot.writeI32(self.refusedAmount)
      oprot.writeFieldEnd()
    if self.payedAmount is not None:
      oprot.writeFieldBegin('payedAmount', TType.I32, 4)
      oprot.writeI32(self.payedAmount)
      oprot.writeFieldEnd()
    if self.payedSum is not None:
      oprot.writeFieldBegin('payedSum', TType.DOUBLE, 5)
      oprot.writeDouble(self.payedSum)
      oprot.writeFieldEnd()
    if self.refusedSum is not None:
      oprot.writeFieldBegin('refusedSum', TType.DOUBLE, 6)
      oprot.writeDouble(self.refusedSum)
      oprot.writeFieldEnd()
    if self.accountNumber is not None:
      oprot.writeFieldBegin('accountNumber', TType.STRING, 7)
      oprot.writeString(self.accountNumber.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.comment is not None:
      oprot.writeFieldBegin('comment', TType.STRING, 8)
      oprot.writeString(self.comment.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class loadTfomsPayments_result(object):
  """
  Attributes:
   - success
   - nfExc
  """

  thrift_spec = (
    (0, TType.MAP, 'success', (TType.I32,None,TType.STRING,None), None, ), # 0
    (1, TType.STRUCT, 'nfExc', (NotFoundException, NotFoundException.thrift_spec), None, ), # 1
  )

  def __init__(self, success=None, nfExc=None,):
    self.success = success
    self.nfExc = nfExc

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.MAP:
          self.success = {}
          (_ktype101, _vtype102, _size100 ) = iprot.readMapBegin() 
          for _i104 in xrange(_size100):
            _key105 = iprot.readI32();
            _val106 = iprot.readString().decode('utf-8')
            self.success[_key105] = _val106
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.nfExc = NotFoundException()
          self.nfExc.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('loadTfomsPayments_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.MAP, 0)
      oprot.writeMapBegin(TType.I32, TType.STRING, len(self.success))
      for kiter107,viter108 in self.success.items():
        oprot.writeI32(kiter107)
        oprot.writeString(viter108.encode('utf-8'))
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.nfExc is not None:
      oprot.writeFieldBegin('nfExc', TType.STRUCT, 1)
      self.nfExc.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
